import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BinaryBackground from "../components/BinaryBackground";
import Script from "next/script";
import { Providers } from "./providers";
import AskBbiWidget from '../components/AskBbiWidget';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "M. Ibraheem Zaffar / Devibbi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            // Simple script to check for dark mode preference
            try {
              if (localStorage.getItem('darkMode') === 'true' || 
                  (localStorage.getItem('darkMode') === null && 
                   window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark');
                document.documentElement.classList.remove('light');
              } else {
                document.documentElement.classList.remove('dark');
                document.documentElement.classList.add('light');
              }
            } catch (e) {}
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Facebook SDK */}
        <Script strategy="afterInteractive" id="facebook-jssdk">
          {`
            window.fbAsyncInit = function() {
              FB.init({
                appId: '1234567890', // Replace with your Facebook App ID
                xfbml: true,
                version: 'v18.0'
              });
            };

            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "https://connect.facebook.net/en_US/sdk.js";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
          `}
        </Script>
        <Providers>
          <BinaryBackground />
          {children}
          <AskBbiWidget />
        </Providers>
      </body>
    </html>
  );
}
